### PR TITLE
Document --artifact-path for backups

### PR DESCRIPTION
**Pull request by gcapizzi**
/cc @MirahImage

### CODE REVIEW

**Comment by cshollingsworth** [comment]
Hey, @gcapizzi -- is this applicable to 2.1, or are there other versions this change should be pulled into, as well?

**Comment by gcapizzi** [comment]
Hi @cshollingsworth ! This is applicable to all versions, but will only work with the next release of BBR (which we haven't released yet), so I'm not sure how we should handle this, I guess we should probably wait for the feature to be released?

**Comment by ghanna2017** [comment]
Merged per @thereses . Thanks @gcapizzi

**Comment by gcapizzi** [comment]
This will need to be backported to older versions too. @ghanna2017 can you do this for us?

**Comment by ghanna2017** [comment]
Hi @gcapizzi - I'll leave that to @kdolor-pivotal since she's the lead on this.

**Comment by kdolor-pivotal** [comment]
Hi @gcapizzi I'm seeing that this is published to the Cloud Foundry Docs https://docs.cloudfoundry.org/bbr/index.html, rather than the commercial docs that have different version branches. 

Can you provide links to where else you would like this information to appear? Thanks.

**Comment by gcapizzi** [comment]
Hi @kdolor-pivotal, you are absolutely right, I think I got a bit confused :) we can close this, thanks!

**Pull request merged**
