### PR TITLE
Docs improvements for BBR including external blobstore addition

### PR DESCRIPTION
**Pull request by flangewad**
Corresponds to https://github.com/cloudfoundry/docs-book-cloudfoundry/pull/76

### CODE REVIEW

**Comment by jncd** [comment]
Thanks for this big body of work. @flangewad 
We'll merge and give it an edit; and, reach out if we have questions.

**Comment by jncd** [comment]
I did the merge but would like to work with you more on this to rationalize it a bit more and make it really stronger and safer doc. I think you're both in the UK, which makes timing hard to meet. Do you have time on Friday afternoon, say 4 pm (GMT) / 8 am (PST)?

**Comment by flangewad** [comment]
Hi Jane,

It would be great to pair with you on this :)

Unfortunately we have a team meeting 4pm GMT Friday which is hard to move.
I can be available until 7pm Thursday, if that works for you?

Rosie

**Comment by flangewad** [comment]
Hi @jncd let me know if you can make your Thursday morning, otherwise I'm sure we can arrange something for next week :)

**Pull request merged**
